spring.application.name=employee-api

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/employee_db}
spring.datasource.username=${DATABASE_USERNAME:bojan}
spring.datasource.password=${DATABASE_PASSWORD:bojan}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL:false}

spring.jackson.serialization.write-dates-as-timestamps=false